# Generated by Django 5.1.4 on 2025-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
