# Generated by Django 5.1.4 on 2025-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
